apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctr-pull
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ctr-pull
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ctr-pull
subjects:
- kind: ServiceAccount
  name: ctr-pull
roleRef:
  kind: ClusterRole
  name: ctr-pull
  apiGroup: rbac.authorization.k8s.io
